### GET request to example server
GET http://localhost:8080/employees

###
POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "Guy"
}

###
POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "Dude",
  "email": "Dude@gmail.com"
}

###
GET http://localhost:8080/employees/search?name=Guy

###
GET http://localhost:8080/employees/1000

###
POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "Test",
  "email": "test@gmail.com"
}
###
PUT http://localhost:8080/employees/5
Content-Type: application/json

{
  "name": "Updated",
  "email": "updated@gmail.com"
}
###
DELETE http://localhost:8080/employees/5